#!/usr/bin/env bash
target_dir="$HOME/.local/bin"

if [ ! -d $target_dir ]; then
	mkdir -p $target_dir
fi

for cm in git-*; do
	chmod +x $cm
	ln -sf "$PWD/$cm" "$target_dir/$cm" && echo "Installed $cm"
done
